version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-d)su@&h)r5wbhio8$dxr9u*nnvzw76c(9_t^*^qlv@1f@!-uyj"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:15
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"